# Generated by Django 5.1.1 on 2025-10-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_vencimiento',
            new_name='fecha_limite',
        ),
        migrations.AddField(
            model_name='tarea',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
